with open("src/lib/civic-database.ts", "r") as f:
    text = f.read()

new_officials = """  { slug: 'chuck-schumer', name: 'Chuck Schumer', title: 'U.S. Senator', level: 'Federal', party: 'Democratic', district: 'New York', color: '#2563eb', initials: 'CS', score: 82, promises: 45, bills: 120, votes: 1500, detail: 'Senate Majority Leader from New York.', office: '322 Hart Senate Office Building', phone: '(202) 224-6542', email: 'senator@schumer.senate.gov', nextElection: 'November 7, 2028', coordinates: [-73.9352, 40.7306] },
  { slug: 'mitch-mcconnell', name: 'Mitch McConnell', title: 'U.S. Senator', level: 'Federal', party: 'Republican', district: 'Kentucky', color: '#dc2626', initials: 'MM', score: 70, promises: 30, bills: 80, votes: 1800, detail: 'Senate Minority Leader from Kentucky.', office: '317 Russell Senate Office Building', phone: '(202) 224-2541', email: 'senator@mcconnell.senate.gov', nextElection: 'November 3, 2026', coordinates: [-84.8733, 37.8393] },
  { slug: 'nancy-pelosi', name: 'Nancy Pelosi', title: 'U.S. Representative', level: 'Federal', party: 'Democratic', district: 'California · District 11', color: '#2563eb', initials: 'NP', score: 85, promises: 50, bills: 200, votes: 2000, detail: 'Representative from California.', office: '1236 Longworth House Office Building', phone: '(202) 225-4965', email: 'contact@pelosi.house.gov', nextElection: 'November 5, 2024', coordinates: [-122.4194, 37.7749] },
  { slug: 'kevin-mccarthy', name: 'Kevin McCarthy', title: 'U.S. Representative', level: 'Federal', party: 'Republican', district: 'California · District 20', color: '#dc2626', initials: 'KM', score: 68, promises: 35, bills: 100, votes: 1600, detail: 'Representative from California.', office: '2468 Rayburn House Office Building', phone: '(202) 225-2915', email: 'contact@mccarthy.house.gov', nextElection: 'November 5, 2024', coordinates: [-119.0187, 35.3733] },
  { slug: 'ted-cruz', name: 'Ted Cruz', title: 'U.S. Senator', level: 'Federal', party: 'Republican', district: 'Texas', color: '#dc2626', initials: 'TC', score: 75, promises: 40, bills: 90, votes: 1200, detail: 'Senator from Texas.', office: '127A Russell Senate Office Building', phone: '(202) 224-5922', email: 'contact@cruz.senate.gov', nextElection: 'November 5, 2024', coordinates: [-97.7431, 30.2672] },
  { slug: 'alexandria-ocasio-cortez', name: 'Alexandria Ocasio-Cortez', title: 'U.S. Representative', level: 'Federal', party: 'Democratic', district: 'New York · District 14', color: '#2563eb', initials: 'AOC', score: 90, promises: 60, bills: 150, votes: 800, detail: 'Representative from New York.', office: '229 Cannon House Office Building', phone: '(202) 225-3965', email: 'contact@ocasio-cortez.house.gov', nextElection: 'November 5, 2024', coordinates: [-73.8449, 40.8448] },
  { slug: 'bernie-sanders', name: 'Bernie Sanders', title: 'U.S. Senator', level: 'Federal', party: 'Independent', district: 'Vermont', color: '#10b981', initials: 'BS', score: 88, promises: 55, bills: 130, votes: 1900, detail: 'Senator from Vermont.', office: '332 Dirksen Senate Office Building', phone: '(202) 224-5141', email: 'contact@sanders.senate.gov', nextElection: 'November 5, 2024', coordinates: [-72.5778, 44.2601] },
  { slug: 'elizabeth-warren', name: 'Elizabeth Warren', title: 'U.S. Senator', level: 'Federal', party: 'Democratic', district: 'Massachusetts', color: '#2563eb', initials: 'EW', score: 86, promises: 48, bills: 110, votes: 1400, detail: 'Senator from Massachusetts.', office: '309 Hart Senate Office Building', phone: '(202) 224-4543', email: 'contact@warren.senate.gov', nextElection: 'November 5, 2024', coordinates: [-71.0589, 42.3601] },
  { slug: 'mitt-romney', name: 'Mitt Romney', title: 'U.S. Senator', level: 'Federal', party: 'Republican', district: 'Utah', color: '#dc2626', initials: 'MR', score: 72, promises: 28, bills: 75, votes: 1100, detail: 'Senator from Utah.', office: '354 Russell Senate Office Building', phone: '(202) 224-5251', email: 'contact@romney.senate.gov', nextElection: 'November 5, 2024', coordinates: [-111.8910, 40.7608] },
  { slug: 'cory-booker', name: 'Cory Booker', title: 'U.S. Senator', level: 'Federal', party: 'Democratic', district: 'New Jersey', color: '#2563eb', initials: 'CB', score: 84, promises: 42, bills: 105, votes: 1300, detail: 'Senator from New Jersey.', office: '717 Hart Senate Office Building', phone: '(202) 224-3224', email: 'contact@booker.senate.gov', nextElection: 'November 5, 2024', coordinates: [-74.1724, 40.7357] },
  { slug: 'rand-paul', name: 'Rand Paul', title: 'U.S. Senator', level: 'Federal', party: 'Republican', district: 'Kentucky', color: '#dc2626', initials: 'RP', score: 74, promises: 38, bills: 85, votes: 1250, detail: 'Senator from Kentucky.', office: '167 Russell Senate Office Building', phone: '(202) 224-4343', email: 'contact@paul.senate.gov', nextElection: 'November 5, 2024', coordinates: [-84.5204, 38.0315] },
  { slug: 'amy-klobuchar', name: 'Amy Klobuchar', title: 'U.S. Senator', level: 'Federal', party: 'Democratic', district: 'Minnesota', color: '#2563eb', initials: 'AK', score: 83, promises: 40, bills: 115, votes: 1350, detail: 'Senator from Minnesota.', office: '425 Dirksen Senate Office Building', phone: '(202) 224-3244', email: 'contact@klobuchar.senate.gov', nextElection: 'November 5, 2024', coordinates: [-93.2650, 44.9778] },
"""

insert_pos = text.find("  { slug: 'ron-desantis'")
if insert_pos != -1:
    text = text[:insert_pos] + new_officials + text[insert_pos:]

with open("src/lib/civic-database.ts", "w") as f:
    f.write(text)
