import React from 'react';

import { Link } from 'react-router-dom';
import { FormEvent, useState } from 'react';
import { Icon } from './icons';
import { Logo } from './site-chrome';

export function AuthExperience({ mode }: { mode: 'sign-in' | 'sign-up' }) {
  const [email, setEmail] = useState('');
  const [completed, setCompleted] = useState(false);
  const isSignUp = mode === 'sign-up';
  const submit = (event: FormEvent) => { event.preventDefault(); if (email.trim()) setCompleted(true); };
  return <section className="auth-page"><div className="auth-visual"><div className="auth-visual-grid" /><div className="auth-visual-content"><Logo inverse /><span className="auth-kicker">CIVICLENZ MEMBER ACCESS</span><h1>{isSignUp ? 'Your civic picture starts with your address.' : 'Your officials. Your follows. Your voice.'}</h1><p>Save the offices and issues you care about, then receive only the updates you choose.</p><div className="auth-visual-points"><span><Icon name="shield" size={18} /> Private account controls</span><span><Icon name="bell" size={18} /> Meaningful alerts, not noise</span><span><Icon name="file" size={18} /> Source-backed public records</span></div></div></div><div className="auth-form-side"><Link className="auth-back" to="/"><Icon name="arrow-left" size={16} /> Back to CivicLenZ</Link><div className="auth-card">{completed ? <Success mode={mode} email={email} /> : <><span className="small-label">{isSignUp ? 'JOIN CIVICLENZ' : 'WELCOME BACK'}</span><h2>{isSignUp ? 'Create your free account' : 'Sign in to CivicLenZ'}</h2><p>{isSignUp ? 'No password needed for the first release. We will send a secure confirmation code.' : 'Use your email to receive a secure one-time sign-in code.'}</p><button className="auth-google" type="button" onClick={() => setCompleted(true)}><span className="google-g">G</span> Continue with Google</button><div className="auth-divider"><span>or continue with email</span></div><form onSubmit={submit}><label>Email address<input type="email" required value={email} onChange={(event) => setEmail(event.target.value)} placeholder="you@example.com" /></label>{isSignUp ? <label className="auth-checkbox"><input type="checkbox" required /><span>I agree to the <Link to="/research/">privacy policy</Link> and member terms.</span></label> : null}<button className="btn btn-primary btn-large auth-submit" type="submit">{isSignUp ? 'Send confirmation code' : 'Send sign-in code'} <Icon name="arrow-right" size={17} /></button></form><p className="auth-switch">{isSignUp ? 'Already have an account?' : 'New to CivicLenZ?'} <Link to={isSignUp ? '/sign-in/' : '/sign-up/'}>{isSignUp ? 'Log in' : 'Create an account'}</Link></p></>}</div><p className="auth-note"><Icon name="lock" size={14} /> Prototype flow only. Production auth will use Google OAuth or a Resend-issued email code.</p></div></section>;
}

function Success({ mode, email }: { mode: 'sign-in' | 'sign-up'; email: string }) { return <div className="auth-success"><span><Icon name="mail" size={31} /></span><h2>Check your inbox</h2><p>In the completed product, a one-time code would be sent to <b>{email || 'your email address'}</b>. This branch demonstrates the screen and flow only; no email was sent.</p><Link className="btn btn-primary btn-large" to="/dashboard/">Preview the dashboard <Icon name="arrow-right" size={17} /></Link><button type="button" className="text-button" onClick={() => window.location.reload()}>{mode === 'sign-up' ? 'Use another email' : 'Try a different sign-in'}</button></div>; }
